export type ElecProduct = {
  id: number;
  title: string;
  price: number;
  was?: number;
  img: string;
  group: string;
  sub?: string;
  brand: string;
  condition: "New" | "Used" | "Refurbished";
  grade: "Excellent" | "Good" | "Very Good";
  verified: boolean;
  rating: number;
  reviews: number;
  seller: string;
  shipping: string;
  format: "fixed" | "auction";
  city: string;
  href: string;
  short?: string;
};

export const elecGroups = [
  {
    id: "cameras",
    name: "Cameras & Photo",
    children: ["DSLR Cameras", "Mirrorless Cameras", "Point & Shoot Cameras", "Lenses", "Camera Accessories"],
  },
  { id: "phones", name: "Cell Phones & Accessories", children: ["Smartphones", "Smartwatches", "Cases"] },
  { id: "computers", name: "Computers/Tablets & Networking", children: ["Laptops", "Desktops", "Tablets"] },
  { id: "appliances", name: "Major Appliances", children: ["Refrigerators", "Washers"] },
  { id: "smart-home", name: "Surveillance & Smart Home Electronics", children: ["Cameras", "Speakers"] },
  { id: "tv-audio", name: "TV, Video & Home Audio", children: ["Televisions", "Headphones"] },
  { id: "vehicle", name: "Vehicle Electronics & GPS", children: ["GPS", "Car audio"] },
  { id: "games", name: "Video Games & Consoles", children: ["Consoles", "Games"] },
  { id: "vr", name: "Virtual Reality", children: ["Headsets"] },
] as const;

export const elecProducts: ElecProduct[] = [
  {
    id: 7,
    title: "iPhone 14 Pro 128GB – Deep Purple",
    short: "iPhone 14 Pro",
    price: 72000,
    was: 95000,
    img: "/categories/trend-phone.jpg",
    group: "phones",
    sub: "Smartphones",
    brand: "Apple",
    condition: "Refurbished",
    grade: "Excellent",
    verified: true,
    rating: 4.8,
    reviews: 1232,
    seller: "TechWorld",
    shipping: "Free shipping",
    format: "fixed",
    city: "Kathmandu",
    href: "/listing/7",
  },
  {
    id: 1,
    title: 'MacBook Air M1 2020 13" – Space Gray',
    short: "MacBook Air",
    price: 96000,
    was: 120000,
    img: "/categories/trend-laptop.jpg",
    group: "computers",
    sub: "Laptops",
    brand: "Apple",
    condition: "Refurbished",
    grade: "Excellent",
    verified: true,
    rating: 4.7,
    reviews: 856,
    seller: "GadgetHub",
    shipping: "Free shipping",
    format: "fixed",
    city: "Kathmandu",
    href: "/listing/1",
  },
  {
    id: 21,
    title: "Samsung Galaxy S22 256GB – Phantom Black",
    short: "Samsung Galaxy",
    price: 55000,
    was: 70000,
    img: "/categories/trend-phones.jpg",
    group: "phones",
    sub: "Smartphones",
    brand: "Samsung",
    condition: "Refurbished",
    grade: "Good",
    verified: true,
    rating: 4.6,
    reviews: 642,
    seller: "MobileMart",
    shipping: "Free shipping",
    format: "fixed",
    city: "Pokhara",
    href: "/listing/21",
  },
  {
    id: 2,
    title: "Sony WH-1000XM4 Headphones",
    short: "Sony Headphones",
    price: 14500,
    was: 22000,
    img: "/categories/trend-headphones.jpg",
    group: "tv-audio",
    sub: "Headphones",
    brand: "Sony",
    condition: "Refurbished",
    grade: "Good",
    verified: true,
    rating: 4.8,
    reviews: 1189,
    seller: "SoundZone",
    shipping: "Free shipping",
    format: "fixed",
    city: "Kathmandu",
    href: "/listing/2",
  },
  {
    id: 5,
    title: "PlayStation 5 Disc Edition",
    short: "PlayStation 5",
    price: 48000,
    was: 65000,
    img: "/categories/trend-console.jpg",
    group: "games",
    sub: "Consoles",
    brand: "Sony",
    condition: "Refurbished",
    grade: "Very Good",
    verified: true,
    rating: 4.7,
    reviews: 534,
    seller: "GameNest",
    shipping: "Free shipping",
    format: "auction",
    city: "Lalitpur",
    href: "/listing/5",
  },
  {
    id: 3,
    title: "Galaxy Watch6 44mm",
    short: "Smart Watches",
    price: 18999,
    was: 26999,
    img: "/categories/trend-watch.jpg",
    group: "phones",
    sub: "Smartwatches",
    brand: "Samsung",
    condition: "New",
    grade: "Excellent",
    verified: true,
    rating: 4.5,
    reviews: 410,
    seller: "GadgetHub",
    shipping: "Free shipping",
    format: "auction",
    city: "Kathmandu",
    href: "/listing/3",
  },
  {
    id: 22,
    title: "DSLR Camera 24MP Body",
    price: 64000,
    was: 78000,
    img: "/categories/trend-camera.jpg",
    group: "cameras",
    sub: "DSLR Cameras",
    brand: "PhotoLab",
    condition: "Used",
    grade: "Good",
    verified: true,
    rating: 4.4,
    reviews: 188,
    seller: "LensHouse",
    shipping: "Free shipping",
    format: "fixed",
    city: "Pokhara",
    href: "/listing/22",
  },
  {
    id: 23,
    title: "Mirrorless Camera with Lens",
    price: 82000,
    was: 99000,
    img: "/promo/camera.png",
    group: "cameras",
    sub: "Mirrorless Cameras",
    brand: "PhotoLab",
    condition: "Refurbished",
    grade: "Excellent",
    verified: true,
    rating: 4.6,
    reviews: 96,
    seller: "LensHouse",
    shipping: "NPR 250 shipping",
    format: "fixed",
    city: "Kathmandu",
    href: "/listing/23",
  },
  {
    id: 24,
    title: '11" Tablet 128GB',
    price: 32000,
    was: 41000,
    img: "/categories/elec-tablet.jpg",
    group: "computers",
    sub: "Tablets",
    brand: "Samsung",
    condition: "Refurbished",
    grade: "Excellent",
    verified: true,
    rating: 4.5,
    reviews: 277,
    seller: "TechWorld",
    shipping: "Free shipping",
    format: "fixed",
    city: "Lalitpur",
    href: "/listing/24",
  },
  {
    id: 25,
    title: '55" 4K Smart Television',
    price: 54000,
    was: 69000,
    img: "/shop/shop-tv.png",
    group: "tv-audio",
    sub: "Televisions",
    brand: "Samsung",
    condition: "New",
    grade: "Excellent",
    verified: false,
    rating: 4.3,
    reviews: 151,
    seller: "HomeScreen",
    shipping: "NPR 500 shipping",
    format: "fixed",
    city: "Kathmandu",
    href: "/listing/25",
  },
];

export function npr(amount: number) {
  return `NPR ${amount.toLocaleString("en-IN")}`;
}

export function discount(product: ElecProduct) {
  if (!product.was || product.was <= product.price) return null;
  return Math.round((1 - product.price / product.was) * 100);
}
